import { createClientFromRequest } from 'npm:@base44/sdk@0.8.31';

function slot(){const p=Object.fromEntries(new Intl.DateTimeFormat('en-CA',{timeZone:'America/Sao_Paulo',year:'numeric',month:'2-digit',day:'2-digit',hour:'2-digit',hour12:false}).formatToParts(new Date()).map(x=>[x.type,x.value]));const h=Number(p.hour||0),day=`${p.year}-${p.month}-${p.day}`;if(h<3){const n=h+1;return{hour:n,window:`${String(n).padStart(2,'0')}:00-${String(n+1).padStart(2,'0')}:00`,at:new Date(`${day}T${String(n).padStart(2,'0')}:00:00-03:00`)}}if(h<13)return{hour:13,window:'13:00-14:00',at:new Date(`${day}T13:00:00-03:00`)};const t=new Date(`${day}T12:00:00-03:00`);t.setDate(t.getDate()+1);const d=new Intl.DateTimeFormat('en-CA',{timeZone:'America/Sao_Paulo',year:'numeric',month:'2-digit',day:'2-digit'}).format(t);return{hour:0,window:'00:00-01:00',at:new Date(`${d}T00:00:00-03:00`)}}
const active=(c:any)=>!['archived','ended','deleted'].includes(String(c.state||c.status||'').toLowerCase());

Deno.serve(async(req)=>{try{
 const b=createClientFromRequest(req),x=await req.json().catch(()=>({})),auth=await b.auth.isAuthenticated().catch(()=>false);
 if(!auth&&!x._service_role)return Response.json({ok:false,error:'Não autorizado'},{status:401});
 if(!x.amazon_account_id)return Response.json({ok:false,error:'amazon_account_id obrigatório'},{status:400});
 const s=slot(),campaigns=await b.asServiceRole.entities.Campaign.filter({amazon_account_id:x.amazon_account_id},'-updated_at',5000).catch(()=>[]);let auto=0,exact=0,existing=0;
 for(const c of campaigns.filter(active)){const name=String(c.name||c.campaign_name||''),target=String(c.targeting_type||'').toUpperCase(),asin=String(c.asin||'').trim();if(!asin)continue;
  if(target==='AUTO'||name.toUpperCase().startsWith('AUTO |')){const q=await b.asServiceRole.entities.AutoCampaignRepairQueue.filter({amazon_account_id:x.amazon_account_id,asin,status:'scheduled'},'-created_date',1).catch(()=>[]);if(q.length)existing++;else{await b.asServiceRole.entities.AutoCampaignRepairQueue.create({amazon_account_id:x.amazon_account_id,asin,campaign_id:c.campaign_id?String(c.campaign_id):null,campaign_name:name||null,status:'scheduled',queue_hour:s.hour,queue_window:s.window,scheduled_at:s.at.toISOString(),attempt_count:0,max_attempts:5});auto++;}await b.asServiceRole.entities.Campaign.update(c.id,{completion_status:'verification_pending',repair_status:'scheduled',repair_queue_window:s.window,repair_scheduled_at:s.at.toISOString()}).catch(()=>{});}
  if(target==='MANUAL'&&name.toUpperCase().includes('EXACT')){const kws=await b.asServiceRole.entities.Keyword.filter({amazon_account_id:x.amazon_account_id,campaign_id:String(c.campaign_id),match_type:'exact'},'-updated_at',100).catch(()=>[]),enabled=kws.filter((k:any)=>['enabled','active'].includes(String(k.state||k.status||'').toLowerCase()));if(enabled.length&&c.completion_status==='complete')continue;const q=await b.asServiceRole.entities.KeywordRepairQueue.filter({amazon_account_id:x.amazon_account_id,asin,status:'scheduled'},'-created_date',1).catch(()=>[]);if(q.length)existing++;else{await b.asServiceRole.entities.KeywordRepairQueue.create({amazon_account_id:x.amazon_account_id,asin,campaign_id:c.campaign_id?String(c.campaign_id):null,ad_group_id:c.ad_group_id?String(c.ad_group_id):null,status:'scheduled',queue_hour:s.hour,queue_window:s.window,scheduled_at:s.at.toISOString(),attempt_count:0});exact++;}await b.asServiceRole.entities.Campaign.update(c.id,{completion_status:'incomplete',is_incomplete:true,repair_status:'scheduled',repair_queue_window:s.window,repair_scheduled_at:s.at.toISOString(),last_repair_error:enabled.length?null:'Grupo EXACT sem palavra-chave ativa confirmada.'}).catch(()=>{});}
 }
 return Response.json({ok:true,prepared_at:new Date().toISOString(),queue_window:s.window,scheduled_at:s.at.toISOString(),campaigns_scanned:campaigns.length,auto_repairs_queued:auto,exact_keyword_repairs_queued:exact,already_queued:existing,total_new_repairs:auto+exact,message:`Todos os reparos foram preparados antes da janela ${s.window}.`});
}catch(e){return Response.json({ok:false,error:e?.message||'Erro ao preparar reparos'},{status:500});}});
