import {makeEntities} from 'file:///app/server/src/sdk/entities.ts';import {sql} from 'file:///app/server/src/db.ts';
import {availableAdsStock,hasFreshAdsInventory} from 'file:///app/base44/shared/stockAdsPolicy.ts';
import {productOfferEligibility} from 'file:///app/base44/shared/productCampaignPauseGuard.ts';
import {resolveConfiguredBidPolicy} from 'file:///app/base44/shared/configuredBidPolicy.ts';
const aid='6a40448b9af1241f356e9fcc',db=makeEntities(),token=Deno.env.get('API_TOKEN')||Deno.env.get('ADMIN_PASSWORD')||'',operation='user_fan_buyability_recovery_20261009';
async function call(name,payload={}){const r=await fetch('http://127.0.0.1:8000/functions/'+name,{method:'POST',headers:{'content-type':'application/json','x-api-token':token},body:JSON.stringify({_service_role:true,amazon_account_id:aid,...payload}),signal:AbortSignal.timeout(360000)});const d=await r.json();if(!r.ok||d.ok===false)throw Error(name+': '+JSON.stringify(d.error||d.errors||d));return d;}
async function ads(path,method,payload,type){return (await call('amazonAdsCommand',{path,method,payload,operation,content_type:'application/vnd.'+type+'.v3+json',accept:'application/vnd.'+type+'.v3+json'})).payload;}
async function list(path,type,key,filter={}){const rows=[];let nextToken;do{const d=await ads(path,'POST',{...filter,maxResults:1000,...(nextToken?{nextToken}:{})},type);rows.push(...(d?.[key]||[]));nextToken=d?.nextToken;}while(nextToken);return rows;}
const norm=s=>String(s||'').trim().toUpperCase();
try{
 const {listingBuyability}=await import('file:///app/base44/shared/listingOfferStatus.ts');
 if(!listingBuyability([{status:['BUYABLE']}],[{severity:'ERROR',enforcements:{actions:[{action:'ATTRIBUTE_SUPPRESSED'}]}}]).buyable)throw Error('New buyability policy not deployed');
 await call('syncAmazonOfferAvailability',{skus:['FBA-0024b'],max_products:20});await call('syncProductCatalogV2');
 const products=await db.Product.filter({amazon_account_id:aid},'id',5000),settings=(await db.PerformanceSettings.filter({amazon_account_id:aid},'-updated_at',1))[0];if(Number(settings.daily_budget_limit)!==100)throw Error('Unexpected account spending cap');
 const p=products.find(p=>p.sku==='FBA-0024b'&&p.catalog_sync_status==='success');if(!p||!hasFreshAdsInventory(p)||availableAdsStock(p)<=0||p.listing_buyable!==true||p.offer_active!==true)throw Error('Fan not eligible after fresh Amazon verification');
 for(const alias of products.filter(x=>x.asin===p.asin&&x.campaign_pause_lock===true))await db.Product.update(alias.id,{campaign_pause_lock:false,campaign_pause_lock_reason:null,campaign_pause_reason:null,pause_reason:null,ads_pause_reason:null,ads_scope_status:alias.ads_scope_status==='manual_block'?'authorized':alias.ads_scope_status,campaign_pause_locked_by:operation,updated_at:new Date().toISOString()});
 const created=await call('createAutoCampaignForAsin',{asin:p.asin,sku:p.sku,product_name:p.display_name||p.product_name,launch_at_minimum:true});const cid=String(created.campaign_id||'');if(!cid)throw Error('No fan campaign');
 const filter={campaignIdFilter:{include:[cid]}},bp=resolveConfiguredBidPolicy(settings),floor=Math.min(bp.ceiling,Math.max(.45,bp.minBid));
 const groups=await list('/sp/adGroups/list','spAdGroup','adGroups',filter),pas=await list('/sp/productAds/list','spProductAd','productAds',filter),targets=await list('/sp/targets/list','spTargetingClause','targetingClauses',filter);
 const pa=pas.find(a=>a.sku===p.sku&&a.asin===p.asin&&a.state!=='ARCHIVED'),group=groups.find(g=>String(g.adGroupId)===String(pa?.adGroupId)&&g.state!=='ARCHIVED');if(!pa||!group)throw Error('Fan missing group/ad');
 const gid=String(group.adGroupId),own=targets.filter(t=>String(t.adGroupId)===gid&&t.state!=='ARCHIVED'),old=Number(group.defaultBid||floor);
 const previous=await db.AdsBidChangeLog.filter({amazon_account_id:aid,source:operation},'-created_at',20);const factor=previous.length?1:1.15;
 const newDefault=Math.round(Math.min(bp.ceiling,Math.max(floor,old*factor))*100)/100;
 await ads('/sp/adGroups','PUT',{adGroups:[{adGroupId:gid,state:'ENABLED',defaultBid:newDefault}]},'spAdGroup');if(pa.state!=='ENABLED')await ads('/sp/productAds','PUT',{productAds:[{adId:String(pa.adId),state:'ENABLED'}]},'spProductAd');
 const updates=own.map(t=>({targetId:String(t.targetId),state:'ENABLED',bid:Math.round(Math.min(bp.ceiling,Math.max(floor,Number(t.bid||old)*factor))*100)/100}));if(updates.length)await ads('/sp/targets','PUT',{targetingClauses:updates},'spTargetingClause');
 const actualTargets=await list('/sp/targets/list','spTargetingClause','targetingClauses',filter);for(const u of updates){const t=actualTargets.find(t=>String(t.targetId)===u.targetId);if(t?.state!=='ENABLED'||Number(t.bid)!==u.bid)throw Error('Fan target readback failed');if(!previous.length)await db.AdsBidChangeLog.create({amazon_account_id:aid,campaign_id:cid,ad_group_id:gid,target_id:u.targetId,sku:p.sku,asin:p.asin,old_bid:Number(own.find(t=>String(t.targetId)===u.targetId)?.bid||old),new_bid:u.bid,source:operation,status:'confirmed',amazon_confirmed:true,reason:'User requested all stocked products active; corrected false block from non-suppressing image issue',created_at:new Date().toISOString()});}
 await db.Product.update(p.id,{has_campaign:true,campaign_status:'active',linked_campaign_id:cid,ads_resume_pending:false,kickoff_status:'completed'});
 console.log('FAN_RECOVERED='+JSON.stringify({sku:p.sku,asin:p.asin,fba:availableAdsStock(p),campaign_id:cid,old_default_bid:old,new_default_bid:newDefault,targets:updates,listing_buyable:true}));
 const canonical=new Map();for(const product of products.filter(p=>hasFreshAdsInventory(p)&&availableAdsStock(p)>0).sort((a,b)=>availableAdsStock(b)-availableAdsStock(a)))if(!canonical.has(product.asin))canonical.set(product.asin,product);
 let campaigns=await list('/sp/campaigns/list','spCampaign','campaigns',{stateFilter:{include:['ENABLED']}}),allAds=await list('/sp/productAds/list','spProductAd','productAds',{stateFilter:{include:['ENABLED']}}),allGroups=await list('/sp/adGroups/list','spAdGroup','adGroups',{stateFilter:{include:['ENABLED']}});
 const gset=new Set(allGroups.map(g=>String(g.adGroupId)));const tiny=campaigns.filter(c=>c.targetingType==='AUTO'&&Number(c.budget?.budget)<5&&allAds.some(a=>String(a.campaignId)===String(c.campaignId)&&[...canonical.values()].some(p=>p.asin===a.asin&&norm(p.sku)===norm(a.sku))));
 if(tiny.length){const locals=await db.Campaign.filter({amazon_account_id:aid},'id',10000);const adj=tiny.map(c=>({campaign_id:String(c.campaignId),db_id:locals.find(l=>String(l.campaign_id||l.amazon_campaign_id)===String(c.campaignId))?.id,new_budget:5,reason:'User requested active discovery for all stocked products; remove sub-R$5 nominal budget bottleneck'})).filter(a=>a.db_id);if(adj.length)console.log('DISCOVERY_BUDGET_REPAIR='+JSON.stringify(await call('adjustCampaignBudgets',{adjustments:adj})));campaigns=await list('/sp/campaigns/list','spCampaign','campaigns',{stateFilter:{include:['ENABLED']}});}
 const autos=campaigns.filter(c=>c.targetingType==='AUTO');const autoIds=autos.map(c=>String(c.campaignId));const allTargets=await list('/sp/targets/list','spTargetingClause','targetingClauses',{campaignIdFilter:{include:autoIds},stateFilter:{include:['ENABLED']}});
 const coverage=[];for(const product of canonical.values()){const matches=allAds.filter(a=>a.asin===product.asin&&norm(a.sku)===norm(product.sku)&&gset.has(String(a.adGroupId))&&autos.some(c=>String(c.campaignId)===String(a.campaignId))&&allTargets.some(t=>String(t.adGroupId)===String(a.adGroupId)));
 const entry={sku:product.sku,asin:product.asin,fba:availableAdsStock(product),active_auto:matches.length>0,campaigns:matches.map(a=>({id:a.campaignId,budget:autos.find(c=>String(c.campaignId)===String(a.campaignId))?.budget?.budget,default_bid:allGroups.find(g=>String(g.adGroupId)===String(a.adGroupId))?.defaultBid,active_targets:allTargets.filter(t=>String(t.adGroupId)===String(a.adGroupId)).length}))};coverage.push(entry);console.log('FINAL_PRODUCT_COVERAGE='+JSON.stringify(entry));}
 await call('syncAdsCampaignStatesV2');console.log('FINAL_ACCOUNT_SPEND='+JSON.stringify(await call('updateDailySpendController')));
 console.log('FINAL_COVERAGE_TOTAL='+JSON.stringify({stocked_products:coverage.length,with_active_auto:coverage.filter(p=>p.active_auto).length,without_active_auto:coverage.filter(p=>!p.active_auto),daily_spend_cap:settings.daily_budget_limit}));
}finally{await sql.end();}
